<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006~2018 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: liu21st <liu21st@gmail.com>
// +----------------------------------------------------------------------

return [
    '__pattern__' => [
        'name' => '\w+',
    ],
    '[hello]'     => [
        ':id'   => ['index/hello', ['method' => 'get'], ['id' => '\d+']],
        ':name' => ['index/hello', ['method' => 'post']],
    ],
    //前端
    'test'=>'index/Test/test',
    'index'=>'index/index/index',
    'loginout'=>'index/index/loginout',
    'addfeng'=>'index/addfeng/index',
    'deal'=>'index/deal/index',
    'move'=>'index/move/index',
    'sell'=>'index/sell/index',
    'buy'=>'index/buy/index',
    'usercenter'=>'index/usercenter/index',
    'delorder'=>'index/usercenter/del',
    'payvip'=>'index/usercenter/payvip',
    'getstate'=>'index/usercenter/getstate',
    'evals'=>'index/evals/index',
    'aboutme'=>'index/aboutme/index',
    'serves'=>'index/serves/index',
    'servesnews'=>'index/servesnews/index',
    'prodetail'=>'index/prodetail/index',
    'newdetail'=>'index/newdetail/index',
    'productdetail'=>'index/productdetail/index',
    'postorder'=>'index/productdetail/postorder',
    'checklogin'=>'index/productdetail/checklogin',
    'registers'=>'index/Login/registers',
    'sendcode'=>'index/Login/sendcode',
    'loginsms'=>'index/Login/loginsms',
    'checkphoneishave'=>'index/Login/checkphoneishave',
    'upmoreimg'=>'index/Sell/upImg',
    'delimgindex'=>'index/Sell/del',
    'TZ'=>'index/Notify/wxPayTz',
    'TZSm'=>'index/Notify/wxPayTzSm',
    'TZser'=>'index/Notify/wxPayTzser',
    'TZwx'=>'index/Notify/wxPayTzwx',
    'login'=>'index/Login/index',
    'payforcode'=>'index/Login/payforcode',
    'addserver'=>'index/Addserver/index',
    'serpay'=>'index/Addserver/serpay',
    //api接口
    'myapi'=>'index/Myapi/wxlogin',
    'getuseropenid'=>'index/Myapi/getuseropenid',
    'sendsms'=>'index/Myapi/sendcode',
    'register'=>'index/Myapi/register',
    'dologin'=>'index/Myapi/doLogin',
    'getprice'=>'index/Myapi/getprice',
    'wxpay'=>'index/Myapi/wxpay',
    'getbanner'=>'index/Myapi/getbanner',
    'gettype'=>'index/Myapi/gettype',
    'gettoptype'=>'index/Myapi/gettoptype',
    'findhao'=>'index/Myapi/findhao',
    'haolist'=>'index/Myapi/haolist',
    'sellnotifi'=>'index/Myapi/sellnotifi',
    'getdetail'=>'index/Myapi/getdetail',
    'dealwxlogin'=>'index/Myapi/dealwxlogin',
    'gethaotype'=>'index/Myapi/gethaotype',
    'apiLoadimg'=>'index/Myapi/apiLoadimg',
    'getxieyi'=>'index/Myapi/getxieyi',
    //后端
    'admin/user'=>'admin/Userlist/index',
    'orderlist'=>'admin/Orderlist/index',
    'admin/viporder'=>'admin/Orderlist/viporder',
    'admin/myorder'=>'admin/Orderlist/myorder',
    'admin/serorder'=>'admin/Orderlist/serorder',
    'admin/details'=>'admin/Orderlist/details',
    'admin/index'=>'admin/Index/index',
    'configs'=>'admin/Index/index',
    'uploadimg'=>'admin/Index/upImg',
    'delimg'=>'admin/Index/delone',
    'del'=>'admin/Index/del',
    'admin/banner'=>'admin/banner/index',
    'addbanner'=>'admin/banner/addbanner',
    'admin/adminlist'=>'admin/adminlist/index',
    'changestate'=>'admin/adminlist/changestate',
    'admin/login'=>'admin/login/index',
    'admin/loginout'=>'admin/login/loginout',
    'admin/permission'=>'admin/permission/index',
    'addpermission'=>'admin/permission/addpermission',
    'admin/typelist'=>'admin/typelist/index',
    'addtype'=>'admin/typelist/addtype',
    'admin/haotype'=>'admin/haotype/index',
    'addhaotype'=>'admin/haotype/addtype',
    'adminadd'=>'admin/adminlist/adminadd',
    'admin/sernewlist'=>'admin/sernewlist/index',
    'addnews'=>'admin/sernewlist/addnews',
    'admin/addserver'=>'admin/addserver/index',
    'addser'=>'admin/addserver/addser',
    'admin/serproblist'=>'admin/serproblist/index',
    'xieyi'=>'admin/Xieyi/index',
    'addxieyi'=>'admin/Xieyi/addxieyi',
    'addprob'=>'admin/serproblist/addprob',
    'selllist'=>'admin/selllist/index',
    'stoppass'=>'admin/selllist/stoppass',
    'reason'=>'admin/selllist/reason',
    'detail'=>'admin/selllist/detail',
];
